services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686"    # Jaeger UI
      - "6831:6831/udp"  # Jaeger agent UDP
    networks:
      - app-network

networks:
  app-network:
    external: true
